# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "E:/CODE/cmpe140/assignment6/ProcessorHardwareValidation/ProcessorHardwareValidation.runs/synth_1/mips_fpga.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 4
set_param general.usePosixSpawnForFork 1
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/CODE/cmpe140/assignment6/ProcessorHardwareValidation/ProcessorHardwareValidation.cache/wt [current_project]
set_property parent.project_path E:/CODE/cmpe140/assignment6/ProcessorHardwareValidation/ProcessorHardwareValidation.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/CODE/cmpe140/assignment6/ProcessorHardwareValidation/ProcessorHardwareValidation.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  E:/CODE/cmpe140/assignment6/ProcessorHardwareValidation/ProcessorHardwareValidation.srcs/sources_1/imports/lab/adder.v
  E:/CODE/cmpe140/assignment6/ProcessorHardwareValidation/ProcessorHardwareValidation.srcs/sources_1/imports/lab/alu.v
  E:/CODE/cmpe140/assignment6/ProcessorHardwareValidation/ProcessorHardwareValidation.srcs/sources_1/imports/lab/auxdec.v
  E:/CODE/cmpe140/assignment6/ProcessorHardwareValidation/ProcessorHardwareValidation.srcs/sources_1/imports/lab/button_debouncer.v
  E:/CODE/cmpe140/assignment6/ProcessorHardwareValidation/ProcessorHardwareValidation.srcs/sources_1/imports/lab/clk_gen.v
  E:/CODE/cmpe140/assignment6/ProcessorHardwareValidation/ProcessorHardwareValidation.srcs/sources_1/imports/lab/controlunit.v
  E:/CODE/cmpe140/assignment6/ProcessorHardwareValidation/ProcessorHardwareValidation.srcs/sources_1/imports/lab/datapath.v
  E:/CODE/cmpe140/assignment6/ProcessorHardwareValidation/ProcessorHardwareValidation.srcs/sources_1/imports/lab/dmem.v
  E:/CODE/cmpe140/assignment6/ProcessorHardwareValidation/ProcessorHardwareValidation.srcs/sources_1/imports/lab/dreg.v
  E:/CODE/cmpe140/assignment6/ProcessorHardwareValidation/ProcessorHardwareValidation.srcs/sources_1/imports/lab/hex_to_7seg.v
  E:/CODE/cmpe140/assignment6/ProcessorHardwareValidation/ProcessorHardwareValidation.srcs/sources_1/imports/lab/imem.v
  E:/CODE/cmpe140/assignment6/ProcessorHardwareValidation/ProcessorHardwareValidation.srcs/sources_1/imports/lab/led_mux.v
  E:/CODE/cmpe140/assignment6/ProcessorHardwareValidation/ProcessorHardwareValidation.srcs/sources_1/imports/lab/maindec.v
  E:/CODE/cmpe140/assignment6/ProcessorHardwareValidation/ProcessorHardwareValidation.srcs/sources_1/imports/lab/mips.v
  E:/CODE/cmpe140/assignment6/ProcessorHardwareValidation/ProcessorHardwareValidation.srcs/sources_1/imports/lab/mips_top.v
  E:/CODE/cmpe140/assignment6/ProcessorHardwareValidation/ProcessorHardwareValidation.srcs/sources_1/imports/lab/mux2.v
  E:/CODE/cmpe140/assignment6/ProcessorHardwareValidation/ProcessorHardwareValidation.srcs/sources_1/imports/lab/regfile.v
  E:/CODE/cmpe140/assignment6/ProcessorHardwareValidation/ProcessorHardwareValidation.srcs/sources_1/imports/lab/signext.v
  E:/CODE/cmpe140/assignment6/ProcessorHardwareValidation/ProcessorHardwareValidation.srcs/sources_1/imports/lab/mips_fpga.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/CODE/cmpe140/assignment6/ProcessorHardwareValidation/ProcessorHardwareValidation.srcs/constrs_1/imports/lab/mips_fpga.xdc
set_property used_in_implementation false [get_files E:/CODE/cmpe140/assignment6/ProcessorHardwareValidation/ProcessorHardwareValidation.srcs/constrs_1/imports/lab/mips_fpga.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental E:/CODE/cmpe140/assignment6/ProcessorHardwareValidation/ProcessorHardwareValidation.srcs/utils_1/imports/synth_1/mips_fpga.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top mips_fpga -part xc7a35tcpg236-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mips_fpga.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file mips_fpga_utilization_synth.rpt -pb mips_fpga_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
